---
- hosts: all
  vars:
    hydra_user: tulhydra
    nodejs_version: v0.10.4
    ruby_version: 2.2.4
    hydra_version: 7.1.0
    jdk_version: 8
    jdk_release: 65
    domainname: localhost
  tasks:
    - name: Install dumb init
      get_url: dest=/usr/bin/dumb-init url=https://github.com/Yelp/dumb-init/releases/download/v1.0.2/dumb-init_1.0.2_amd64 mode=0775 validate_certs=no
    - include: tasks/devtools.yml
    - include: tasks/nodejs.yml
    - include: tasks/hydra_user.yml
    - include: tasks/devenv.yml
    - include: tasks/ruby.yml
      remote_user: "{{ hydra_user }}"
