---
- hosts: all
  sudo: yes
  vars:
    hydrauser: 'vagrant'
    nodejs_version: v0.10.4
    ruby_version: '2.1.4'
    hydra_version: '7.1.0'
    jdk_version: '8'
    jdk_release: '65'
    domainname: localhost
  tasks:
    - include: tasks/devtools.yml
    - include: tasks/nodejs.yml node_version='{{ nodejs_version}}'
    - include: tasks/ruby.yml version='{{ ruby_version }}' username='{{ hydrauser }}'
