---
# Install rbenv-sudo and default ruby
- name: Clone Hydra App
  git:
    repo: https://github.com/skng5/{{ app_name }}.git
    dest: "{{ app_path }}"
    version: develop
- name: Set owner to the App User
  file:
    path: "{{ app_path }}"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    state: directory
