# Intall NodeJS
- name: download nodejs
  unarchive: src=http://nodejs.org/dist/{{ node_version }}/node-{{ node_version }}.tar.gz dest=/tmp copy=no
- name: configure nodejs
  command: ./configure
  args:
    chdir: /tmp/node-{{ node_version }}
- name: build nodejs
  command: make -C /tmp/node-{{ node_version }}
- name: install nodejs
  command: make -C /tmp/node-{{ node_version }} install
